travis:
  secure:
    BINSTAR_TOKEN: WWog562N5JupwN5p8o14vgcmqPGnnpB+zK0g99iqheNWUnfUuqIOSqstRdh7hcKYNT4grgNcsSctKzLWEJUcK7ywbD66gZDw/ZMtwFZeIrjziRa/HPC9W+xzAk3Ve0+D55kNyRCkdWFS/4t4uoUOgAzm86irwciKm4JQ/0VdWCohjtO2S3HxRF0OtWatZS0/tC1Kxdj4URh7rLLV097+REA6oiGXwrVZFEZ0SvFpV3h6A9JYd4vl/pppisT2nzktgg0xmYRx/cxJ9obMN02uTu//EAe4RiApniUXipAHLCQkh6D44keuHz18vZgGaio0CueegTf3o3vRPboXQZ4KLzoXbyuGwtZjZqUv7KYNsnYuBQHEHE8GcYBx1gOg540AWq4MKhTdENWOR3iSdm+eeme+Au7tSPq49ikKkxB6G5t/MN/LElY6Gt3Pc8bcX7SYgJdLBwowevEdB6VN0uvFopef4dbTwaEZFFk8KQFAvXoFWRwL9lzZMgRBNlZ0RzxRRZ5x3EZpDYk+ZVHIOFe43iO4iilFo90LrWms6gyoYj5Q3hl0b33ALFOghogP45/i6tgpmcHICkQvW+S83zHADZDXDAWSSIluACf5IuG0wBZ0Mxk76hSz8Ub2mqDXTFnNbTI3MsxDXU5F4mI1s0JmjykMY6X4V0z/NtZ3ZfJjvrY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
